name: Download data from RKI
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.**'
      - 'data/*'
      - 'R/maintenance/*'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/README.**'
      - 'data/*'
      - 'R/maintenance/*'
  schedule:
      - cron: '0 */1 * * *'
jobs:
  update-data:
    name: Download and extract data
    runs-on: "macos-latest"
    steps:
      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: 'release'
      - name: install vaccc19de
        run: |
          install.packages('remotes')
          remotes::install_github("friep/vaccc19de")
          install.packages('glue')
          install.packages('readr')
        shell: Rscript {0}
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: "Download data"
        run: |
          source('R/download_and_update.R')
        shell: Rscript {0}
      - name: "Read datenstand and check whether data was updated" 
        id: check-whether-updated
        run: |
          DATENSTAND=$(cat /tmp/datenstand.txt)
          IS_UPDATED=1; [ "$DATENSTAND" == "No update" ] || res=0
          echo $DATENSTAND
          echo $IS_UPDATED
          echo "::set-output name=DATENSTAND::$DATENSTAND"
          echo "::set-output name=IS_UPDATED::IS_UPDATED"
      - name: Commit changes
        uses: EndBug/add-and-commit@v5
        if:  ${{ steps.check-whether-updated.outputs.IS_UPDATED == 1 }}
        with:
          author_name: "GitHub Action"
          author_email: bot_user@frie.codes
          message: format('{{Update with data from {0}}}', ${{steps.check-whether-updated.outputs.DATENSTAND}})
          add: "data/ --force"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      